### ISSUE TITLE
fs-force-utils is missing 

### ISSUE THREAD

**Issue by svishnuv** [ksxnodemodules/fs-force-mkdir-sync#1]
[ERROR] npm ERR! Cloning into bare repository '/ngs/app/cibuildd/.npm/_git-remotes/git-github-com-ksxnodemodules-fs-force-utils-git-v0-0-0-81400d71'...
[ERROR] npm ERR! ssh: connect to host github.com port 22: Connection refused
[ERROR] npm ERR! fatal: Could not read from remote repository.
[ERROR] npm ERR! 
[ERROR] npm ERR! Please make sure you have the correct access rights
[ERROR] npm ERR! and the repository exists.
[ERROR] npm ERR!

**Comment by KSXGitHub** [comment]
Please check your connection, make sure that you use latest version of npm and git.

[This](https://askubuntu.com/questions/610940/ssh-connect-to-host-github-com-port-22-connection-refused) might be helpful
